### ISSUE TITLE
Modify hostname modal missing margins

### ISSUE THREAD

**Issue by sman591** [ComputerScienceHouse/starrs-web#1]
See screenshot - the "modify" modal for a hostname is missing the margin/padding that wraps the modal body.

<img width="625" alt="screenshot 2016-09-06 07 56 09" src="https://cloud.githubusercontent.com/assets/1441807/18279279/c8ec8c8a-7409-11e6-90ea-bce93990d1e4.png">

**Comment by stevenmirabito** [comment]
Confirmed, thanks for reporting! I'll take a look and we should be able to push a fix in the next deploy.

**Comment by stevenmirabito** [comment]
The fix for this issue has been made and deployed. Thanks again!
