### ISSUE TITLE
Leading or trailing spaces in addresses cause api.get_address_range() to fail

### ISSUE THREAD

**Issue by antiduh** [ComputerScienceHouse/starrs-web#2]
Attempting to add the address " 2620:8d:8000:e49::41" to my interface (note the leading space) causes the below failure:

`ERROR: invalid input syntax for type inet: " 2620:8d:8000:e49::41" LINE 1: SELECT api.get_address_range(' 2620:8d:8000:e49::41') ^`

Removing the space fixes the issue.

**Comment by stevenmirabito** [comment]
I've noticed this as well, the backend doesn't strip whitespace before sending it to Postgres. Should be easy enough to fix for the next deploy. Thanks for reporting!

**Comment by stevenmirabito** [comment]
The fix for this issue has been made and deployed. Thanks again!
